# default Profile
spring:
  profiles:
    active: "build"
    # build profile이 실행되면 secret도 함께 실행
    group:
      "build": "secret"

---
# build config
spring:
  config:
    activate:
      on-profile: "build"
  datasource:
    url: "jdbc:mysql://localhost:3308/test?serverTimezone=Asia/Seoul"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
  data:
    redis:
      host: localhost
      port: 6380
---
# local config
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: "jdbc:mysql://local-db:3306/test?serverTimezone=Asia/Seoul"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  data:
    redis:
      host: redis
      port: 6379
